name: Publish Docker image and Deploy to AWS

on:
  push:
    branches:
      - develop

env:
  NODE_ENV: production
  DB_PORT: 5432
  DB_HOST: db
  POSTGRES_DB: prod_db
  POSTGRES_USER: user
  POSTGRES_PASSWORD: user
  BACKEND_PORT: 8000
  FRONTEND_PORT: 80
  BACKEND_HOST: doctoo.org
  JWT_EXPIRATION_TIME: 1d
  JWT_REFRESH_TOKEN_EXPIRATION_TIME: 7d
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  JWT_REFRESH_TOKEN_SECRET: ${{ secrets.JWT_REFRESH_TOKEN_SECRET }}
  GOOGLE_AUTH_CLIENT_ID: ${{ secrets.GOOGLE_AUTH_CLIENT_ID }}
  GOOGLE_AUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_AUTH_CLIENT_SECRET }}
  MAIL_HOST: smtp.gmail.com
  MAIL_FROM: doctoo
  MAIL_PORT: 587
  MAIL_USER: ${{ secrets.MAIL_USER }}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  AWS_S3_REGION: ${{ secrets.AWS_REGION }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GOOGLE_CLOUD_HEALTHCARE_NLP_API_PROJECT_ID: summarization-clinical-notes
  GOOGLE_CLOUD_HEALTHCARE_NLP_API_PRIVATE_KEY_ID: 229c9dfba0bf4f3545ef6b8fd88c9ca42622f16b
  GOOGLE_CLOUD_HEALTHCARE_NLP_API_PRIVATE_KEY: |
    "-----BEGIN PRIVATE
    KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDWFjb7zQpqIn6N\nT1LAjerDdgu8MrtaSmpJeZbCu1W6c772+06rTTQ1gUqwT1luMQ0LLSBPtfX6LBBr\n7YU44385XT3X1PS1/UGISDuIa3w47141y37xQ8sqUj+GEypHJGd6nTQanrk9zZV4\ntok4bBN5BxWPrIxvBGTjKSN1ItNq/M1czVoZmeVwu8RbGgnq47BFhAI0DegNMANe\nviqR8qhcehIqUFmnk3Td7G6L/mZZHoTgVFRCqzlGwtiy7xWYikdDH6hJFAcnXjwh\nDlYxB7g9u6IUGADV864AZ+dlO3xP7liSDZO3wFUHB+fEaC48Kb+zbonjksT/Lcup\n7MKyHYWvAgMBAAECggEABpkPSTUL0JVnuJfxoS25laXvKZNwOQfC2qj/LmLkGHtY\nQp9HqVIrGr8JGWQ+zn1rvUJcixrQcGqoUHFcOEPFFcMeRc6BDIFB/9nr48bPVEVB\n0LomahVAjyCm3U1VcbBPTLncVerrcdCMkeTSkpPj9W/DJfcXoEZsKYz+8ZnEAwhD\nqI8f9wO97MEmwu1/FqWYtFsttdMnO1wjkaDGOnLn/zT7d7Dr0Ic7tfGA2ipeqxjR\ngVmdOfUm4gX0PDaBwawhqUd1mVaGFy19h5bErYyAjlxuSSJCSlhNYxOGrnLhG/TJ\ndU4oOCy3BTXT7aj2WzJBnI8h6ZCVuf0WBwbUmoLFWQKBgQD6xB5SVeCrfNojz5lA\niwDr+kkRGv6MhHe9OZMRYRhiV3IlyLqc00IuHkzlzSZ+tdV7jRSUhWpTeHt5Fy3e\nALrwxUSyhk/3mn+fftVpJhbQU/PPCzL5m0LpRHm1BNG8XmAIbasisk9Pl7yXtfX8\nXiv4ySQ/K4+a7T/mu/NfoW1iqwKBgQDajhz4f4qez0pfM5136p3KkahxYpS1Nzuf\nUSUmVaGZnBPDCOZ/zBoj619glFDhtZUbG2CcVWZO7Nrz0CxLCmTO92P6uEnt7o6X\n7xnC1bG0S7MDrE9YNl/NISJrBqnco3atAcDZsR08c9ZbNPO6c4OqdaCk+M4MswJ5\nWJEo8UaJDQKBgEuFLsCLHmtm4WcxiSzX8AIhUUn2gDyfVFRHd5QfUrGjNjxM1G6Q\nbPjopS3796DncBCSb2U/PMNAoKbaJTUbsTD7p/G/42tlOxQ0pV7SWsKI1f8/ly12\n5dLMjX7HocaCAZfoN0buvlXxE5n48cj8L2/wW5suqkP1OW5qoiPlwMSbAoGAMSD5\nCjNBaemXAkeMAkTPK5YKk1Jhs0qzMGEBRNjC9tDK8HCzv86VobVrPz6X3+T9m5ZP\n5VSdJui/X0dQbZ3sg0nBQ77hf4a8rxKka9O1mp3Zo928CExQxL/KCNz6mgp0xvc5\n7rWNqOUxLld84lDNLCg88FitmNU0nSp3lwiFnpECgYEA6rtXwm2FdSHe5MSuon4H\nMGf90AZJSsUiW/rJZDy9ERyjrRIA5/5x8f5HqFaGTv/OYKMsGjv8InqpEc5f0S21\nXv1MFDUr3Uf+vJenPYUm/1YbOL2j44V9f01+ZJgxcrKglv7l6CaWPLD2FQPXT+6K\nHd7459byyHODKhb6+yGn3VY=\n-----END
    PRIVATE KEY-----\n"
  GOOGLE_CLOUD_HEALTHCARE_NLP_API_CLIENT_EMAIL: summarization-clinical-notes@summarization-clinical-notes.iam.gserviceaccount.com
  GOOGLE_CLOUD_HEALTHCARE_NLP_API_CLIENT_ID: 109664033001444324022
  GOOGLE_CLOUD_HEALTHCARE_NLP_API_REGION: europe-west4
  GOOGLE_CLOUD_HEALTHCARE_NLP_API_PROJECT_NAME: summarization-clinical-notes
  USER_DEFAULT_AVATAR: https://doctoo-bucket-prod.s3.eu-central-1.amazonaws.com/avatars/fefd2de1-330e-48ab-a8d1-4306291896d8.png
  REACT_APP_USER_DEFAULT_AVATAR: https://doctoo-bucket-prod.s3.eu-central-1.amazonaws.com/avatars/fefd2de1-330e-48ab-a8d1-4306291896d8.png
  REACT_APP_GOOGLE_AUTH_CLIENT_ID: 296889536498-63dlvj3gtomf2n53j9ggoconqks6qg3s.apps.googleusercontent.com
  REACT_APP_GOOGLE_AUTH_CLIENT_SECRET: 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
  TWO_FA_APP_NAME: doctoo
  STRIPE_SECRET_KEY: sk_test_51NnOHIK6algMCn4zhmgBroyITfIpBlg9NGWowSLmKLDapzkZh1UYBacLWIYEGhh20shxawy6SuqcTjD0tf2CYaMB008E8Dsp6U
  REACT_APP_STRIPE_PUBLISHABLE_KEY: pk_test_51NnOHIK6algMCn4zTEr2WOIBXP1JkVRjcyUybVk90zekyjHL1oTJYrAp0rzEE6S3fpHMVFzZ0O8EN6BGUPnraE9o00pCgPujFr
  STRIPE_CURRENCY: usd
  OPENAI_API_KEY: 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
  OPENAI_API_MODEL: gpt-3.5-turbo
  VIDEOSDK_API_KEY: 4a50e51b-0523-4981-a7d4-e9df3a64c770
  VIDEOSDK_SECRET_KEY: e31ce6498db8a9280592a1ec27e399da3a0010da51df32cfda72898fcdb5a711
  VIDEOSDK_API_ENDPOINT: https://api.videosdk.live/v2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build docker images
        run: |
          cd backend
          docker build -t bilanuk/doctoo-backend:latest -f Dockerfile.prod .
          cd ../frontend
          docker build -t bilanuk/doctoo-frontend:latest -f Dockerfile.prod .
          cd ../email-microservice
          docker build -t bilanuk/doctoo-email:latest -f Dockerfile.prod .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push bilanuk/doctoo-backend:latest
          docker push bilanuk/doctoo-frontend:latest
          docker push bilanuk/doctoo-email:latest

      - name: Install AWS CLI 2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Install ecs-cli
        run: |
          sudo curl -Lo /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
          sudo chmod +x /usr/local/bin/ecs-cli
          ecs-cli configure profile --profile-name doctoo --access-key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret-key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ecs-cli configure --cluster doctoo-cluster --default-launch-type EC2 --region eu-central-1 --config-name doctoo

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build production.yml from template using envsubst
        run: |
          sudo apt-get update
          sudo apt-get install gettext-base
          envsubst < production.template.yml > production.yml
          echo "production.yml:"
          cat production.yml

      - name: Deploy to AWS
        run: |
          ecs-cli compose --project-name doctoo --file production.yml \
           --debug service up \
           --deployment-max-percent 100 --deployment-min-healthy-percent 0 \
           --region eu-central-1 --ecs-profile doctoo \
           --cluster-config doctoo --create-log-groups
