name: Run tests on backend and frontend

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: 'Run tests on node version 16'
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Prepare shared folder
        run: npm run init
      - name: Run frontend tests
        run: cd frontend && npm test -- --watchAll=false
      - name: Run backend unit tests
        run: cd backend && npm run test
      - name: Run backend e2e mocked unit tests
        run: cd backend && npm run test:e2e-mocked
