FROM node:16-alpine as build

WORKDIR /app

COPY ./package*.json .
RUN npm ci

COPY . .
RUN npm run build

FROM node:16-alpine

WORKDIR /app

COPY ./package*.json .
RUN npm ci --only=production
RUN npm install -g sequelize-cli

COPY --from=build /app/dist ./dist

EXPOSE 6000
CMD ["node", "dist/main.js"]