export const ROUTES = {
  SIGNUP: '/signup',
  VERIFY_REGISTER: '/verify/:token',
  APPOINTMENTS: 'appointments',
  LOGIN: '/login',
  REGISTER_SUCCESS: '/register-success',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password/:token',
  HOME: '/',
  DASHBOARD: '/dashboard',
  MY_DOCTORS: '/my-doctors',
  CALENDAR: '/calendar',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  CHATS: '/chats',
  PAYMENT: '/payment/:appointmentId',
  PASSPORT: '/passport',
  TWO_FA: '/two-fa/verify',
  SEARCH: '/search',
  SUMMARIZATION: '/summarization',
  DOCTORCHAT: '/doctorchat',
  CONFERENCE: '/conference/:id',
  TRANSCRIPT: '/transcript',
};
